### ISSUE TITLE
GUI: Error trying to delete ROA for IPv6 prefix

### ISSUE THREAD

**Issue by fendemann** [dragonresearch/rpki.net#850]
When I try to delete a roa for an IPv6 prefix, I get an error. Delete a roa for IPv4 prefix works.

--------------------------------
rpki.net buildbot-1.0.1476127742

    Home

    Help

Internal Server Error
Whoops! The administrator has been notified of this error.

**Comment by sraustein** [comment]
Anything in logs?

**Comment by fendemann** [comment]
Yes, here from the /var/log/apache2/error.log

**Pressing the DELETE button results in**
[Tue Jan 10 19:50:21.227255 2017] [wsgi:error] [pid 1250:tid 140254886061824] ERROR 2017-01-10 19:50:21,226 django.request Internal Server Error: /rpki/roa/84/delete
[Tue Jan 10 19:50:21.227368 2017] [wsgi:error] [pid 1250:tid 140254886061824] Traceback (most recent call last):
[Tue Jan 10 19:50:21.227378 2017] [wsgi:error] [pid 1250:tid 140254886061824]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
[Tue Jan 10 19:50:21.227383 2017] [wsgi:error] [pid 1250:tid 140254886061824]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jan 10 19:50:21.227388 2017] [wsgi:error] [pid 1250:tid 140254886061824]   File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
[Tue Jan 10 19:50:21.227393 2017] [wsgi:error] [pid 1250:tid 140254886061824]     return view_func(request, *args, **kwargs)
[Tue Jan 10 19:50:21.227397 2017] [wsgi:error] [pid 1250:tid 140254886061824]   File "/usr/lib/python2.7/dist-packages/rpki/gui/decorators.py", line 28, in _tls_required
[Tue Jan 10 19:50:21.227402 2017] [wsgi:error] [pid 1250:tid 140254886061824]     return f(request, *args, **kwargs)
[Tue Jan 10 19:50:21.227434 2017] [wsgi:error] [pid 1250:tid 140254886061824]   File "/usr/lib/python2.7/dist-packages/rpki/gui/app/views.py", line 105, in wrapped_fn
[Tue Jan 10 19:50:21.227440 2017] [wsgi:error] [pid 1250:tid 140254886061824]     return f(request, *args, **kwargs)
[Tue Jan 10 19:50:21.227445 2017] [wsgi:error] [pid 1250:tid 140254886061824]   File "/usr/lib/python2.7/dist-packages/rpki/gui/app/views.py", line 849, in roa_delete
[Tue Jan 10 19:50:21.227449 2017] [wsgi:error] [pid 1250:tid 140254886061824]     for route in roa.routes:
[Tue Jan 10 19:50:21.227454 2017] [wsgi:error] [pid 1250:tid 140254886061824]   File "/usr/lib/python2.7/dist-packages/rpki/gui/app/models.py", line 312, in routes
[Tue Jan 10 19:50:21.227458 2017] [wsgi:error] [pid 1250:tid 140254886061824]     rng = self.prefixes.filter(version=4)[0].as_resource_range()
[Tue Jan 10 19:50:21.227462 2017] [wsgi:error] [pid 1250:tid 140254886061824]   File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 201, in __getitem__
[Tue Jan 10 19:50:21.227466 2017] [wsgi:error] [pid 1250:tid 140254886061824]     return list(qs)[0]
[Tue Jan 10 19:50:21.227471 2017] [wsgi:error] [pid 1250:tid 140254886061824] IndexError: list index out of range


**Pressing the INFO button results in**
[Tue Jan 10 19:51:22.494850 2017] [wsgi:error] [pid 1250:tid 140254902847232] ERROR 2017-01-10 19:51:22,493 django.request Internal Server Error: /rpki/roa/84/
[Tue Jan 10 19:51:22.495086 2017] [wsgi:error] [pid 1250:tid 140254902847232] Traceback (most recent call last):
[Tue Jan 10 19:51:22.495115 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
[Tue Jan 10 19:51:22.495138 2017] [wsgi:error] [pid 1250:tid 140254902847232]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jan 10 19:51:22.495159 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
[Tue Jan 10 19:51:22.495181 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return view_func(request, *args, **kwargs)
[Tue Jan 10 19:51:22.495200 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/rpki/gui/decorators.py", line 28, in _tls_required
[Tue Jan 10 19:51:22.495220 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return f(request, *args, **kwargs)
[Tue Jan 10 19:51:22.495239 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/rpki/gui/app/views.py", line 105, in wrapped_fn
[Tue Jan 10 19:51:22.495259 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return f(request, *args, **kwargs)
[Tue Jan 10 19:51:22.495278 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/rpki/gui/app/views.py", line 577, in roa_detail
[Tue Jan 10 19:51:22.495297 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return render(request, 'app/roa_detail.html', {'object': obj})
[Tue Jan 10 19:51:22.495316 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/shortcuts.py", line 67, in render
[Tue Jan 10 19:51:22.495336 2017] [wsgi:error] [pid 1250:tid 140254902847232]     template_name, context, request=request, using=using)
[Tue Jan 10 19:51:22.495355 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/loader.py", line 99, in render_to_string
[Tue Jan 10 19:51:22.495375 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return template.render(context, request)
[Tue Jan 10 19:51:22.495394 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/backends/django.py", line 74, in render
[Tue Jan 10 19:51:22.495414 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return self.template.render(context)
[Tue Jan 10 19:51:22.495433 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 210, in render
[Tue Jan 10 19:51:22.495506 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return self._render(context)
[Tue Jan 10 19:51:22.495528 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 202, in _render
[Tue Jan 10 19:51:22.495548 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return self.nodelist.render(context)
[Tue Jan 10 19:51:22.495563 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
[Tue Jan 10 19:51:22.495581 2017] [wsgi:error] [pid 1250:tid 140254902847232]     bit = self.render_node(node, context)
[Tue Jan 10 19:51:22.495600 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
[Tue Jan 10 19:51:22.495619 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return node.render(context)
[Tue Jan 10 19:51:22.495638 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py", line 135, in render
[Tue Jan 10 19:51:22.495658 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return compiled_parent._render(context)
[Tue Jan 10 19:51:22.495676 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 202, in _render
[Tue Jan 10 19:51:22.495695 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return self.nodelist.render(context)
[Tue Jan 10 19:51:22.495747 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
[Tue Jan 10 19:51:22.495766 2017] [wsgi:error] [pid 1250:tid 140254902847232]     bit = self.render_node(node, context)
[Tue Jan 10 19:51:22.495785 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
[Tue Jan 10 19:51:22.495804 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return node.render(context)
[Tue Jan 10 19:51:22.495823 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py", line 135, in render
[Tue Jan 10 19:51:22.495842 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return compiled_parent._render(context)
[Tue Jan 10 19:51:22.495873 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 202, in _render
[Tue Jan 10 19:51:22.495917 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return self.nodelist.render(context)
[Tue Jan 10 19:51:22.495954 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
[Tue Jan 10 19:51:22.495984 2017] [wsgi:error] [pid 1250:tid 140254902847232]     bit = self.render_node(node, context)
[Tue Jan 10 19:51:22.496005 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
[Tue Jan 10 19:51:22.496024 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return node.render(context)
[Tue Jan 10 19:51:22.496040 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
[Tue Jan 10 19:51:22.496067 2017] [wsgi:error] [pid 1250:tid 140254902847232]     result = block.nodelist.render(context)
[Tue Jan 10 19:51:22.496279 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
[Tue Jan 10 19:51:22.496308 2017] [wsgi:error] [pid 1250:tid 140254902847232]     bit = self.render_node(node, context)
[Tue Jan 10 19:51:22.496328 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
[Tue Jan 10 19:51:22.496348 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return node.render(context)
[Tue Jan 10 19:51:22.496392 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/defaulttags.py", line 155, in render
[Tue Jan 10 19:51:22.496413 2017] [wsgi:error] [pid 1250:tid 140254902847232]     values = self.sequence.resolve(context, True)
[Tue Jan 10 19:51:22.496433 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 648, in resolve
[Tue Jan 10 19:51:22.496452 2017] [wsgi:error] [pid 1250:tid 140254902847232]     obj = self.var.resolve(context)
[Tue Jan 10 19:51:22.496494 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 789, in resolve
[Tue Jan 10 19:51:22.496517 2017] [wsgi:error] [pid 1250:tid 140254902847232]     value = self._resolve_lookup(context)
[Tue Jan 10 19:51:22.496537 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 827, in _resolve_lookup
[Tue Jan 10 19:51:22.496556 2017] [wsgi:error] [pid 1250:tid 140254902847232]     current = getattr(current, bit)
[Tue Jan 10 19:51:22.496575 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/rpki/gui/app/models.py", line 312, in routes
[Tue Jan 10 19:51:22.496595 2017] [wsgi:error] [pid 1250:tid 140254902847232]     rng = self.prefixes.filter(version=4)[0].as_resource_range()
[Tue Jan 10 19:51:22.496614 2017] [wsgi:error] [pid 1250:tid 140254902847232]   File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 201, in __getitem__
[Tue Jan 10 19:51:22.496663 2017] [wsgi:error] [pid 1250:tid 140254902847232]     return list(qs)[0]
[Tue Jan 10 19:51:22.496685 2017] [wsgi:error] [pid 1250:tid 140254902847232] IndexError: list index out of range

Nothing in /var/log/rpki/irdbd.log or rpkid.log
